apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/securesign/fulcio?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
    # pipelinesascode.tekton.dev/task: "[.tekton/fulcio-unit-test.yaml]"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: fulcio
    appstudio.openshift.io/component: fulcio-server
    pipelines.appstudio.openshift.io/type: build
  name: fulcio-server-on-pull-request
  namespace: rhtas-tenant
spec:
  params:
  - name: dockerfile
    value: Dockerfile.fulcio-server.rh
  - name: git-url
    value: '{{repo_url}}'
  - name: image-expires-after
    value: 5d
  - name: output-image
    value: quay.io/securesign/fulcio-server:on-pr-{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: build-source-image
    value: "true"
  - name: hermetic
    value: "true"
  - name: prefetch-input
    value: [{"path": ".", "type": "gomod"}, {"path": "./hack/tools", "type": "gomod"}]
  - name: go_unit_test
    value: true
  - name: go_base_image
    value: brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.23@sha256:4805e1cb2d1bd9d3c5de5d6986056bbda94ca7b01642f721d83d26579d333c60
  taskRunSpecs:
    - pipelineTaskName: run-unit-test
      serviceAccountName: appstudio-pipeline
      podTemplate:
        imagePullSecrets:
        - name: brew-registry-pull-secret
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: 'https://github.com/securesign/pipelines.git'
      - name: revision
        value: 'main'
      - name: pathInRepo
        value: 'pipelines/docker-build-oci-ta.yaml'
  taskRunTemplate: {}
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
